name: "add-runtime"
description: "download node runtime binaries"

inputs:
  version:
    description: 'binary version [16.0.0]'
    required: true
  os:
    description: 'operating system [linux-x64]'
    required: true
    default: 'linux-x64'
  target:
    description: 'path where to put binaries [runtime]'
    required: false
    default: 'runtime'

runs:
  using: composite
  steps:
    - id: cache-node
      uses: actions/cache@v4
      with:
        path: node.tar.xz
        key: node-${{ inputs.os }}-${{ inputs.version }}

    - name: download node ${{ inputs.os }}
      if: ${{ steps.cache-node.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 5 -O node.tar.xz "https://nodejs.org/dist/v$VERSION/node-v$VERSION-$OS.tar.xz"
      env:
        VERSION: ${{ inputs.version }}
        OS: ${{ inputs.os }}

    - name: unzip
      shell: bash
      run: |
        mkdir -p $TARGET
        tar -xf node.tar.xz --directory=$TARGET --strip-components=1
      env:
        TARGET: ${{ inputs.target }}

branding:
  icon: refresh-cw
  color: green
