name: "add-runtime"
description: "download node runtime binaries"

inputs:
  version:
    description: 'binary version [16.0.0]'
    required: true
  os:
    description: 'operating system [linux-x64]'
    required: true
    default: 'linux-x64'
  target:
    description: 'path where to put binaries [runtime]'
    required: false
    default: 'runtime'

runs:
  using: composite
  steps:
    - name: node linux64
      shell: bash
      run: |
        wget -O node.tar.xz "https://nodejs.org/dist/v$VERSION/node-v$VERSION-linux-x64.tar.xz"
        mkdir -p $TARGET
        tar -xf node.tar.xz --directory=$TARGET --strip-components=1
        rm node.tar.xz
      env:
        VERSION: ${{ inputs.version }}
        TARGET: ${{ inputs.target }}

branding:
  icon: refresh-cw
  color: green
